### ISSUE TITLE
Подключить тест-кавередж

### ISSUE THREAD

**Issue by DenisVerkhoturov** [DenisVerkhoturov/geney#16]
Подключить в проект библиотеку подсчета процента покрытия кода тестами на основе "мутантов".

**Stryker Mutator QuickStart**: https://stryker-mutator.io/stryker4s/quickstart

**Comment by SergeyKozhin** [comment]
Тест кавередж через Stryker создал несоклько проблем:
1. Неполная поддержка многомодульности, что можно исправить скриптом для проверки всех модулей по отдельности.   
2. Появление в процессе тестирования вечных циклов, которые тратят очень много времни на таймаут. Локально проблема решаема, но интегрировать в CI не представляеться возможным.
