### ISSUE TITLE
Убрать ограничение тестов по времени.

### ISSUE THREAD

**Issue by ArturNurtdinov** [DenisVerkhoturov/geney#50]
Сейчас стоит ограничение в 10 секунд на тест, и когда я писал тест с covid-19, то он не успел выполниться

**Comment by DenisVerkhoturov** [comment]
Изначально ограничение было поставлено для страйкера. Я согласен, что ишью имеет смысл, нужно только решить его не забывая про проблему страйкера, который вешал тесты в бесконечные циклы. Апвоут!:+1:
